language: node_js
script: 'npm run ci'
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "iojs"
  - "lts/*"
  - "node"
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "4"
    - node_js: "5"
    - node_js: "iojs"
    - node_js: "node"
